### ISSUE TITLE
PDF Export is not working

### ISSUE THREAD

**Issue by kuchaale** [datitran/jupyter-presentation-template#1]
Does [this solution](https://github.com/hakimel/reveal.js#pdf-export) to export the presentation to PDF work in your case? I was able to get only first two slides exported into pdf-like view (see the screenshot below).
![image](https://user-images.githubusercontent.com/6815953/27390356-5561437a-56a1-11e7-96ec-603f019485a8.png)

Thanks for your response and great template,
Ales

**Comment by datitran** [comment]
@kuchaale Hey yeh it is possible but very tricky! Actually you have to replace the custom.css with the standard theme. The output doesn't look very good though. Here is an [example](https://www.slideshare.net/DatTran33/pyspark-in-practice-slides). Anyways, I'm planning to redesign the custom.css and build it on top of the standard theme, so that the export would also look well. Stay tuned!

**Comment by datitran** [comment]
@kuchaale Check out the new changes!!! `?print-pdf` works now but it's not very good. I'm using decktape instead. Check out the [generated pdf](https://u7410512.dl.dropboxusercontent.com/u/7410512/presentation_template.pdf) from the demo. The color are changed as well.
